export default {
  effects: {
    wah: {
      byte: 9,
      category: "🎚️ Wah",
      options: [
        { id: "CLYDE", title: "Clyde Wah", onByte: "02", offByte: "" },
        { id: "CRY_BB", title: "Cry Baby", onByte: "04", offByte: "" },
        { id: "V847", title: "V847", onByte: "06", offByte: "" },
        { id: "HORSE_WAH", title: "Horse Wah", onByte: "08", offByte: "" },
        {
          id: "OCTAVE_SHIFT",
          title: "Octave Shift",
          onByte: "0A",
          offByte: "",
        },
      ],
    },
    cmp: {
      byte: 10,
      category: "🎛️ Compressor",
      options: [
        { id: "ROSE_COMP", title: "Rose Comp", onByte: "01", offByte: "41" },
        { id: "K_COMP", title: "K Comp", onByte: "02", offByte: "42" },
        {
          id: "STUDIO_COMP",
          title: "Studio Comp",
          onByte: "03",
          offByte: "43",
        },
        {
          id: "DISTORTION_PLUS",
          title: "Distortion +",
          onByte: "04",
          offByte: "44",
        },
        { id: "RC_BOOST", title: "RC Boost", onByte: "05", offByte: "45" },
        { id: "AC_BOOST", title: "AC Boost", onByte: "06", offByte: "46" },
        { id: "DIST_ONE", title: "Dist One", onByte: "07", offByte: "47" },
        { id: "T_SCREAM", title: "T Scream", onByte: "08", offByte: "48" },
        { id: "BLUES_DRV", title: "Blues Drive", onByte: "09", offByte: "49" },
        {
          id: "MORNING_DRV",
          title: "Morning Drive",
          onByte: "0A",
          offByte: "4A",
        },
        { id: "EAT_DIST", title: "Eat Dist", onByte: "0B", offByte: "4B" },
        { id: "RED_DIRT", title: "Red Dirt", onByte: "0C", offByte: "4C" },
        { id: "CRUNCH", title: "Crunch", onByte: "0D", offByte: "4D" },
        { id: "MUFF_FUZZ", title: "Muff Fuzz", onByte: "0E", offByte: "4E" },
        { id: "KATANA", title: "Katana", onByte: "0F", offByte: "4F" },
        { id: "ST_SINGER", title: "ST Singer", onByte: "10", offByte: "50" },
        { id: "RED_FUZZ", title: "Red Fuzz", onByte: "11", offByte: "51" },
      ],
    },
    gate: {
      byte: 16,
      category: "🚪 Gate",
      options: [
        {
          id: "DEFAULT_GATE",
          title: "Default Gate",
          onByte: "01",
          offByte: "41",
        },
      ],
    },
    efx: {
      byte: 12,
      category: "🎛️ EFX",
      options: [
        {
          id: "DISTORTION_PLUS",
          title: "Distortion +",
          onByte: "02",
          offByte: "",
        },
        { id: "RC_BOOST", title: "RC Boost", onByte: "04", offByte: "" },
        { id: "AC_BOOST", title: "AC Boost", onByte: "06", offByte: "" },
        { id: "DIST_ONE", title: "Dist One", onByte: "08", offByte: "" },
        { id: "T_SCREAM", title: "T Scream", onByte: "0A", offByte: "" },
        { id: "BLUES_DRV", title: "Blues Drive", onByte: "0C", offByte: "" },
        {
          id: "MORNING_DRV",
          title: "Morning Drive",
          onByte: "0E",
          offByte: "",
        },
        { id: "EAT_DIST", title: "Eat Dist", onByte: "10", offByte: "" },
        { id: "RED_DIRT", title: "Red Dirt", onByte: "12", offByte: "" },
        { id: "CRUNCH", title: "Crunch", onByte: "14", offByte: "" },
        { id: "MUFF_FUZZ", title: "Muff Fuzz", onByte: "16", offByte: "" },
        { id: "KATANA", title: "Katana", onByte: "18", offByte: "" },
        { id: "ST_SINGER", title: "ST Singer", onByte: "1A", offByte: "" },
        { id: "RED_FUZZ", title: "Red Fuzz", onByte: "1C", offByte: "" },
        { id: "TOUCH_WAH", title: "Touch Wah", onByte: "1E", offByte: "" },
        { id: "CE_1", title: "CE-1", onByte: "20", offByte: "" },
        { id: "CE_2", title: "CE-2", onByte: "22", offByte: "" },
        { id: "ST_CHORUS", title: "ST. Chorus", onByte: "24", offByte: "" },
        { id: "VIBRATOR", title: "Vibrator", onByte: "26", offByte: "" },
        { id: "DETUNE", title: "Detune", onByte: "28", offByte: "" },
        { id: "FLANGER", title: "Flanger", onByte: "2A", offByte: "" },
        { id: "PHASE_90", title: "Phase 90", onByte: "2C", offByte: "" },
        { id: "PHASE_100", title: "Phase 100", onByte: "2E", offByte: "" },
        { id: "SCF", title: "S.C.F", onByte: "30", offByte: "" },
        { id: "U_VIBE", title: "U-Vibe", onByte: "32", offByte: "" },
        { id: "TREMOLO", title: "Tremolo", onByte: "34", offByte: "" },
        { id: "ROTARY", title: "Rotary", onByte: "36", offByte: "" },
        { id: "HARMONIST", title: "Harmonist", onByte: "38", offByte: "" },
        { id: "SCH_1", title: "SCH-1", onByte: "3A", offByte: "" },
      ],
    },
    amp: {
      byte: 13,
      category: "🎚️ Amp",
      options: [
        { id: "JAZZ_CLEAN", title: "Jazz Clean", onByte: "01", offByte: "41" },
        {
          id: "DELUXE_RVB",
          title: "Deluxe Reverb",
          onByte: "02",
          offByte: "42",
        },
        { id: "BASSMATE", title: "Bassmate", onByte: "03", offByte: "43" },
      ],
    },
    delay: {
      byte: 18,
      category: "🎵 Delay",
      options: [
        {
          id: "DIGITAL_DELAY",
          title: "Digital Delay",
          onByte: "02",
          offByte: "42",
        },
        {
          id: "ANALOG_DELAY",
          title: "Analog Delay",
          onByte: "01",
          offByte: "41",
        },
        {
          id: "MODULATION",
          title: "Modulation",
          onByte: "03",
          offByte: "43",
        },
        {
          id: "TAPE_ECHO",
          title: "Tape Echo",
          onByte: "04",
          offByte: "44",
        },
        {
          id: "REVERSE",
          title: "Reverse",
          onByte: "05",
          offByte: "45",
        },
        {
          id: "PAN_DELAY",
          title: "Pan Delay",
          onByte: "06",
          offByte: "46",
        },
        {
          id: "DUOTIME",
          title: "Duotime",
          onByte: "07",
          offByte: "47",
        },
        {
          id: "PHI_DELAY",
          title: "Phi Delay",
          onByte: "08",
          offByte: "48",
        },
      ],
    },
    reverb: {
      byte: 19,
      category: "🎶 Reverb",
      options: [
        {
          id: "ROOM_REVERB",
          title: "Room Reverb",
          onByte: "02",
          offByte: "",
        },
        {
          id: "HALL_REVERB",
          title: "Hall Reverb",
          onByte: "04",
          offByte: "",
        },
        {
          id: "PLATE_REVERB",
          title: "Plate Reverb",
          onByte: "06",
          offByte: "",
        },
        {
          id: "SPRING_REVERB",
          title: "Spring Reverb",
          onByte: "08",
          offByte: "",
        },
        {
          id: "SHIMMER_REVERB",
          title: "Shimmer Reverb",
          onByte: "0A",
          offByte: "",
        },
        {
          id: "DAMP_REVERB",
          title: "Damp Reverb",
          onByte: "0C",
          offByte: "",
        },
      ],
    },
    sr: {
      byte: 23,
      category: "📡 S/R",
      options: [{ id: "S_R", title: "S/R", onByte: "00", offByte: "01" }],
    },
    vol: {
      byte: 25,
      category: "🔊 Volume",
      options: [{ id: "VOL", title: "Volume", onByte: "01", offByte: "41" }],
    },
    ir: {
      byte: 22,
      category: "🎛️ IR",
      options: [
        { id: "JZ120", title: "JZ120", onByte: "01", offByte: "41" },
        { id: "DR112", title: "DR112", onByte: "02", offByte: "42" },
        { id: "BS410", title: "BS410", onByte: "03", offByte: "43" },
        { id: "A212", title: "A212", onByte: "04", offByte: "44" },
        { id: "TR212", title: "TR212", onByte: "05", offByte: "45" },
        { id: "1960", title: "1960", onByte: "06", offByte: "46" },
        { id: "GB412", title: "GB412", onByte: "07", offByte: "47" },
        { id: "V412", title: "V412", onByte: "08", offByte: "48" },
        {
          id: "SWAMP_THANG",
          title: "Swamp Thang",
          onByte: "15",
          offByte: "55",
        },
        {
          id: "CANNABIS_REX_12",
          title: "Cannabis Rex 12",
          onByte: "16",
          offByte: "56",
        },
        {
          id: "LEGEND_1058",
          title: "Legend 1058",
          onByte: "17",
          offByte: "57",
        },
        { id: "CV-75", title: "CV-75", onByte: "18", offByte: "58" },
        { id: "AGL_DB810", title: "AGL DB810", onByte: "09", offByte: "49" },
        { id: "AMP_SV810", title: "AMP SV810", onByte: "0A", offByte: "4A" },
        { id: "AMP_SV410", title: "AMP SV410", onByte: "0B", offByte: "4B" },
        { id: "AMP_SV212", title: "AMP SV212", onByte: "0C", offByte: "4C" },
        { id: "MKB_410", title: "MKB 410", onByte: "0D", offByte: "4D" },
        { id: "TRC_410", title: "TRC 410", onByte: "0E", offByte: "4E" },
        { id: "EDEN_410", title: "EDEN 410", onByte: "0F", offByte: "4F" },
        {
          id: "BASSGUY_410",
          title: "Bassguy 410",
          onByte: "10",
          offByte: "50",
        },
        { id: "M-D45", title: "M-D45", onByte: "11", offByte: "51" },
        { id: "G-HBIRD", title: "G-HBIRD", onByte: "12", offByte: "52" },
        { id: "G-J15", title: "G-J15", onByte: "13", offByte: "53" },
        { id: "CUSTOM_IR", title: "Custom IR", onByte: "14", offByte: "54" },
      ],
    },
    eq: {
      byte: 14,
      category: "🎛️ EQ",
      options: [
        { id: "6_BAND_EQ", title: "6-Band EQ", onByte: "02", offByte: "" },
        { id: "ALIGN_EQ", title: "Align EQ", onByte: "04", offByte: "" },
        { id: "10_BAND_EQ", title: "10-Band EQ", onByte: "06", offByte: "" },
        { id: "PARA_EQ", title: "Para EQ", onByte: "08", offByte: "" },
      ],
    },
    mod: {
      byte: 18,
      category: "🌊 Modulation",
      options: [
        { id: "CE_1", title: "CE-1", onByte: "02", offByte: "" },
        { id: "CE_2", title: "CE-2", onByte: "04", offByte: "" },
        { id: "ST_CHORUS", title: "Stereo Chorus", onByte: "06", offByte: "" },
        { id: "VIBRATOR", title: "Vibrator", onByte: "08", offByte: "" },
        { id: "DETUNE", title: "Detune", onByte: "0A", offByte: "" },
        { id: "FLANGER", title: "Flanger", onByte: "0C", offByte: "" },
        { id: "PHASE_90", title: "Phase 90", onByte: "0E", offByte: "" },
        { id: "PHASE_100", title: "Phase 100", onByte: "10", offByte: "" },
        { id: "S_C_F", title: "S.C.F", onByte: "12", offByte: "" },
        { id: "U_VIBE", title: "U-Vibe", onByte: "14", offByte: "" },
        { id: "TREMOLO", title: "Tremolo", onByte: "16", offByte: "" },
        { id: "ROTARY", title: "Rotary", onByte: "18", offByte: "" },
        { id: "HARMONIST", title: "Harmonist", onByte: "1A", offByte: "" },
        { id: "SCH_1", title: "SCH-1", onByte: "1C", offByte: "" },
        {
          id: "DISTORTION_PLUS",
          title: "Distortion +",
          onByte: "1E",
          offByte: "",
        },
        { id: "RC_BOOST", title: "RC Boost", onByte: "20", offByte: "" },
        { id: "AC_BOOST", title: "AC Boost", onByte: "22", offByte: "" },
        { id: "DIST_ONE", title: "Dist One", onByte: "24", offByte: "" },
        { id: "T_SCREAM", title: "T Scream", onByte: "26", offByte: "" },
        { id: "BLUES_DRV", title: "Blues Driver", onByte: "28", offByte: "" },
        {
          id: "MORNING_DRV",
          title: "Morning Drive",
          onByte: "2A",
          offByte: "",
        },
        { id: "EAT_DIST", title: "Eat Dist", onByte: "2C", offByte: "" },
        { id: "RED_DIRT", title: "Red Dirt", onByte: "2E", offByte: "" },
        { id: "CRUNCH", title: "Crunch", onByte: "30", offByte: "" },
        { id: "MUFF_FUZZ", title: "Muff Fuzz", onByte: "32", offByte: "" },
        { id: "KATANA", title: "Katana", onByte: "34", offByte: "" },
        { id: "ST_SINGER", title: "ST Singer", onByte: "36", offByte: "" },
        { id: "RED_FUZZ", title: "Red Fuzz", onByte: "38", offByte: "" },
        { id: "TOUCH_WAH", title: "Touch Wah", onByte: "3A", offByte: "" },
      ],
    },
  },
};
