export default {
  amp: {
    knobControlStart: [24, 25, 26, 27, 28, 29, 30, 31],
    category: "🎚️ Amp",
    options: [
      { id: "JAZZ_CLEAN", title: "Jazz Clean", onByte: "01", offByte: "65" },
      {
        id: "DELUXE_RVB",
        title: "Deluxe Reverb",
        onByte: "02",
        offByte: "42",
      },
      { id: "BASSMATE", title: "Bassmate", onByte: "03", offByte: "43" },
      { id: "TWEEDY", title: "Tweedy", onByte: "04", offByte: "44" },
      { id: "TWIN_RVB", title: "Twin Reverb", onByte: "05", offByte: "45" },
      { id: "HIWIRE", title: "Hiwire", onByte: "06", offByte: "46" },
      {
        id: "CALI_CRUNCH",
        title: "Cali Crunch",
        onByte: "07",
        offByte: "47",
      },
      { id: "CLASS_A15", title: "Class A15", onByte: "08", offByte: "48" },
      { id: "CLASS_A30", title: "Class A30", onByte: "09", offByte: "49" },
      { id: "PLEXI_100", title: "Plexi 100", onByte: "0A", offByte: "4A" },
      { id: "PLEXI_45", title: "Plexi 45", onByte: "0B", offByte: "4B" },
      { id: "BRIT_800", title: "Brit 800", onByte: "0C", offByte: "4C" },
      { id: "1987_X_50", title: "1987 X 50", onByte: "0D", offByte: "4D" },
      { id: "SLO_100", title: "SLO 100", onByte: "0E", offByte: "4E" },
      {
        id: "FIREMAN_HBE",
        title: "Fireman HBE",
        onByte: "0F",
        offByte: "4F",
      },
      { id: "DUAL_RECT", title: "Dual Rect", onByte: "10", offByte: "50" },
      { id: "DIE_VH4", title: "Die VH4", onByte: "11", offByte: "51" },
      { id: "VIBRO_KING", title: "Vibro King", onByte: "12", offByte: "52" },
      { id: "BUDDA", title: "Budda", onByte: "13", offByte: "53" },
      { id: "MR_Z_38", title: "Mr. Z 38", onByte: "14", offByte: "54" },
      { id: "SUPER_RVB", title: "Super RVB", onByte: "15", offByte: "55" },
      { id: "BRIT_BLUES", title: "Brit Blues", onByte: "16", offByte: "56" },
      { id: "MATCH", title: "Match", onByte: "17", offByte: "57" },
      { id: "BRIT_2000", title: "Brit 2000", onByte: "18", offByte: "58" },
      { id: "UBER", title: "Uber", onByte: "19", offByte: "59" },
      { id: "AGL", title: "AGL", onByte: "1A", offByte: "5A" },
      { id: "BASSGUY", title: "Bassguy", onByte: "1B", offByte: "5B" },
      { id: "MLD", title: "MLD", onByte: "1C", offByte: "5C" },
      { id: "OPTIMA_AIR", title: "Optima Air", onByte: "1D", offByte: "5D" },
      { id: "STAGEMAN", title: "Stageman", onByte: "1E", offByte: "5E" },
      { id: "DGLASS", title: "Dglass", onByte: "1F", offByte: "5F" },
      { id: "STARLIFT", title: "Starlift", onByte: "20", offByte: "60" },
      { id: "VIVO", title: "Vivo", onByte: "21", offByte: "61" },
      {
        id: "F_PRINCETON",
        title: "F Princeton",
        onByte: "22",
        offByte: "62",
      },
      { id: "LONESTAR", title: "Lonestar", onByte: "23", offByte: "63" },
    ],
  },
};
