export default {
  efx: {
    knobControlStart: [18, 19, 20],
    category: "🎛️ EFX",
    options: [
      {
        id: "DISTORTION_PLUS",
        title: "Distortion +",
        onByte: "02",
        offByte: "42",
      },
      { id: "RC_BOOST", title: "RC Boost", onByte: "04", offByte: "44" },
      { id: "AC_BOOST", title: "AC Boost", onByte: "06", offByte: "46" },
      { id: "DIST_ONE", title: "Dist One", onByte: "08", offByte: "48" },
      {
        id: "T_SCREAM",
        title: "T Scream",
        onByte: "0A",
        offByte: "4A",
        knobs: [
          {
            id: "drive",
            title: "DRIVE",
            range: [0, 100],
            ctrl: 18,
          },
          {
            id: "tone",
            title: "TONE",
            range: [0, 100],
            ctrl: 19,
          },
          {
            id: "level",
            title: "LEVEL",
            range: [0, 100],
            ctrl: 20,
          },
        ],
        dominantColor: "#558B2F",
      },
      {
        id: "BLUES_DRV",
        title: "Blues Drive",
        onByte: "0C",
        offByte: "4C",

        knobs: [
          {
            id: "level",
            title: "LEVEL",
            range: [0, 100],
            ctrl: 18,
          },
          {
            id: "tone",
            title: "TONE",
            range: [0, 100],
            ctrl: 19,
          },
          {
            id: "gain",
            title: "GAIN",
            range: [0, 100],
            ctrl: 20,
          },
        ],
        dominantColor: "#01579B",
      },
      {
        id: "MORNING_DRV",
        title: "Morning Drive",
        onByte: "0E",
        offByte: "4E",
        knobs: [
          {
            id: "volume",
            title: "VOLUME",
            range: [0, 100],
            ctrl: 18,
          },
          {
            id: "drive",
            title: "DRIVE",
            range: [0, 100],
            ctrl: 19,
          },
          {
            id: "tone",
            title: "TONE",
            range: [0, 100],
            ctrl: 20,
          },
        ],
        dominantColor: "#9E9D24",
      },
      {
        id: "EAT_DIST",
        title: "Eat Dist",
        onByte: "10",
        offByte: "50",

        knobs: [
          {
            id: "distortion",
            title: "DISTORTION",
            range: [0, 100],
            ctrl: 18,
          },
          {
            id: "filter",
            title: "FILTER",
            range: [0, 100],
            ctrl: 19,
          },
          {
            id: "volume",
            title: "VOLUME",
            range: [0, 100],
            ctrl: 20,
          },
        ],
        dominantColor: "#9E9D24",
      },
      {
        id: "RED_DIRT",
        title: "Red Dirt",
        onByte: "12",
        offByte: "52",
        knobs: [
          {
            id: "drive",
            title: "DRIVE",
            range: [0, 100],
            ctrl: 18,
          },
          {
            id: "tone",
            title: "TONE",
            range: [0, 100],
            ctrl: 19,
          },
          {
            id: "level",
            title: "LEVEL",
            range: [0, 100],
            ctrl: 20,
          },
        ],
        dominantColor: "#D32F2F",
      },
      {
        id: "CRUNCH",
        title: "Crunch",
        onByte: "14",
        offByte: "54",
        knobs: [
          {
            id: "volume",
            title: "VOLUME",
            range: [0, 100],
            ctrl: 18,
          },
          {
            id: "tone",
            title: "TONE",
            range: [0, 100],
            ctrl: 19,
          },
          {
            id: "gain",
            title: "GAIN",
            range: [0, 100],
            ctrl: 20,
          },
        ],
        dominantColor: "#BF360C",
      },
      {
        id: "MUFF_FUZZ",
        title: "Muff Fuzz",
        onByte: "16",
        offByte: "56",
        knobs: [
          {
            id: "volume",
            title: "VOLUME",
            range: [0, 100],
            ctrl: 18,
          },
          {
            id: "tone",
            title: "TONE",
            range: [0, 100],
            ctrl: 19,
          },
          {
            id: "sustain",
            title: "SUSTAIN",
            range: [0, 100],
            ctrl: 20,
          },
        ],
        dominantColor: "#E0E0E0",
      },
      {
        id: "KATANA",
        title: "Katana",
        onByte: "18",
        offByte: "58",
        knobs: [
          {
            id: "boost",
            title: "BOOST",
            range: [0, 1],
            ctrl: 18,
          },
          {
            id: "volume",
            title: "VOLUME",
            range: [0, 100],
            ctrl: 19,
          },
        ],
        dominantColor: "#BDBDBD",
      },
      {
        id: "ST_SINGER",
        title: "ST Singer",
        onByte: "1A",
        offByte: "5A",
        knobs: [
          {
            id: "volume",
            title: "VOLUME",
            range: [0, 100],
            ctrl: 18,
          },
          {
            id: "gain",
            title: "GAIN",
            range: [0, 100],
            ctrl: 19,
          },
          {
            id: "filter",
            title: "FILTER",
            range: [0, 100],
            ctrl: 20,
          },
        ],
        dominantColor: "#757575",
      },
      {
        id: "RED_FUZZ",
        title: "Red Fuzz",
        onByte: "1C",
        offByte: "5C",
        knobs: [
          {
            id: "gain",
            title: "GAIN",
            range: [0, 100],
            ctrl: 18,
          },
          {
            id: "tone",
            title: "TONE",
            range: [0, 100],
            ctrl: 19,
          },
          {
            id: "output",
            title: "OUTPUT",
            range: [0, 100],
            ctrl: 20,
          },
        ],
        dominantColor: "#BC4646",
      },
      {
        id: "TOUCH_WAH",
        title: "Touch Wah",
        onByte: "1E",
        offByte: "5E",
        knobs: [
          {
            id: "mode",
            title: "MODE",
            range: [0, 3],
            ctrl: 18,
            type: "list",
          },
          {
            id: "decay",
            title: "DECAY",
            range: [0, 100],
            ctrl: 19,
          },
          {
            id: "sensitivity",
            title: "SENS",
            range: [0, 100],
            ctrl: 20,
          },
          {
            id: "upDown",
            title: "Up/Down",
            range: [0, 1],
            ctrl: 21,
          },
        ],
        dominantColor: "#4A148C",
      },
      { id: "CE_1", title: "CE-1", onByte: "20", offByte: "60" },
      { id: "CE_2", title: "CE-2", onByte: "22", offByte: "62" },
      { id: "ST_CHORUS", title: "ST. Chorus", onByte: "24", offByte: "64" },
      { id: "VIBRATOR", title: "Vibrator", onByte: "26", offByte: "66" },
      { id: "DETUNE", title: "Detune", onByte: "28", offByte: "68" },
      { id: "FLANGER", title: "Flanger", onByte: "2A", offByte: "6A" },
      { id: "PHASE_90", title: "Phase 90", onByte: "2C", offByte: "6C" },
      { id: "PHASE_100", title: "Phase 100", onByte: "2E", offByte: "6E" },
      { id: "SCF", title: "S.C.F", onByte: "30", offByte: "70" },
      { id: "U_VIBE", title: "U-Vibe", onByte: "32", offByte: "72" },
      { id: "TREMOLO", title: "Tremolo", onByte: "34", offByte: "74" },
      { id: "ROTARY", title: "Rotary", onByte: "36", offByte: "76" },
      { id: "HARMONIST", title: "Harmonist", onByte: "38", offByte: "78" },
      { id: "SCH_1", title: "SCH-1", onByte: "3A", offByte: "7A" },
    ],
  },
};
