export default {
  mod: {
    byte: 18,
    category: "🌊 Modulation",
    options: [
      { id: "CE_1", title: "CE-1", onByte: "02", offByte: "" },
      { id: "CE_2", title: "CE-2", onByte: "04", offByte: "" },
      { id: "ST_CHORUS", title: "Stereo Chorus", onByte: "06", offByte: "" },
      { id: "VIBRATOR", title: "Vibrator", onByte: "08", offByte: "" },
      { id: "DETUNE", title: "Detune", onByte: "0A", offByte: "" },
      { id: "FLANGER", title: "Flanger", onByte: "0C", offByte: "" },
      { id: "PHASE_90", title: "Phase 90", onByte: "0E", offByte: "" },
      { id: "PHASE_100", title: "Phase 100", onByte: "10", offByte: "" },
      { id: "S_C_F", title: "S.C.F", onByte: "12", offByte: "" },
      { id: "U_VIBE", title: "U-Vibe", onByte: "14", offByte: "" },
      { id: "TREMOLO", title: "Tremolo", onByte: "16", offByte: "" },
      { id: "ROTARY", title: "Rotary", onByte: "18", offByte: "" },
      { id: "HARMONIST", title: "Harmonist", onByte: "1A", offByte: "" },
      { id: "SCH_1", title: "SCH-1", onByte: "1C", offByte: "" },
      {
        id: "DISTORTION_PLUS",
        title: "Distortion +",
        onByte: "1E",
        offByte: "",
      },
      { id: "RC_BOOST", title: "RC Boost", onByte: "20", offByte: "" },
      { id: "AC_BOOST", title: "AC Boost", onByte: "22", offByte: "" },
      { id: "DIST_ONE", title: "Dist One", onByte: "24", offByte: "" },
      { id: "T_SCREAM", title: "T Scream", onByte: "26", offByte: "" },
      { id: "BLUES_DRV", title: "Blues Driver", onByte: "28", offByte: "" },
      {
        id: "MORNING_DRV",
        title: "Morning Drive",
        onByte: "2A",
        offByte: "",
      },
      { id: "EAT_DIST", title: "Eat Dist", onByte: "2C", offByte: "" },
      { id: "RED_DIRT", title: "Red Dirt", onByte: "2E", offByte: "" },
      { id: "CRUNCH", title: "Crunch", onByte: "30", offByte: "" },
      { id: "MUFF_FUZZ", title: "Muff Fuzz", onByte: "32", offByte: "" },
      { id: "KATANA", title: "Katana", onByte: "34", offByte: "" },
      { id: "ST_SINGER", title: "ST Singer", onByte: "36", offByte: "" },
      { id: "RED_FUZZ", title: "Red Fuzz", onByte: "38", offByte: "" },
      { id: "TOUCH_WAH", title: "Touch Wah", onByte: "3A", offByte: "" },
    ],
  },
};
